import PDFDocument from "pdfkit";
import { prisma } from "@/lib/prisma";

export interface PDFOptions {
  pageSize?: "A4" | "Letter";
  includeSolutions?: boolean;
  solutionPlacement?: "back" | "after";
  fontSize?: number;
  fontName?: string;
  margins?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
}

export interface PDFResult {
  buffer: Buffer;
  pageCount: number;
}

export class PDFGenerator {
  private static readonly DEFAULT_OPTIONS: Required<
    Omit<PDFOptions, "margins">
  > & {
    margins: Required<NonNullable<PDFOptions["margins"]>>;
  } = {
    pageSize: "A4",
    includeSolutions: true,
    solutionPlacement: "back",
    fontSize: 10,
    fontName: "Helvetica",
    margins: {
      top: 72,
      bottom: 72,
      left: 72,
      right: 72,
    },
  };

  static async generateBookPDF(
    bookId: string,
    options: PDFOptions = {},
  ): Promise<PDFResult> {
    const opts = {
      ...this.DEFAULT_OPTIONS,
      ...options,
      margins: {
        ...this.DEFAULT_OPTIONS.margins,
        ...(options.margins ?? {}),
      },
    };

    const book = await prisma.book.findUnique({
      where: { id: bookId },
      include: {
        bookPuzzles: {
          include: {
            puzzle: true,
            puzzleVersion: true,
            solution: true,
          },
          orderBy: {
            position: "asc",
          },
        },
      },
    });

    if (!book) {
      throw new Error("Book not found");
    }

    const doc = new PDFDocument({
      size: opts.pageSize === "A4" ? "A4" : "LETTER",
      margins: opts.margins,
      autoFirstPage: false,
      info: {
        Title: book.title,
        Author: "Puzzle Book Generator",
        Subject: `${book.puzzleCount} Word Search Puzzles`,
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));

    let pageCount = 0;

    // Page 1: Cover Page
    pageCount++;
    doc.addPage();
    this.addCoverPage(doc, book);

    // Pages 2+: Each puzzle on its own page
    for (let i = 0; i < book.bookPuzzles.length; i++) {
      const bookPuzzle = book.bookPuzzles[i];
      pageCount++;
      doc.addPage();
      this.addPuzzlePage(doc, bookPuzzle, bookPuzzle.displayNumber, opts);
    }

    // Solutions at the back
    if (opts.includeSolutions && opts.solutionPlacement === "back") {
      pageCount++;
      doc.addPage();
      this.addSolutionsPage(doc, book.bookPuzzles);
    }

    doc.end();

    return new Promise((resolve) => {
      doc.on("end", () => {
        const buffer = Buffer.concat(chunks);
        resolve({ buffer, pageCount });
      });
    });
  }

  private static addCoverPage(doc: PDFKit.PDFDocument, book: any): void {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;

    this.drawDecorativeBorder(doc, pageWidth, pageHeight);

    doc
      .fontSize(36)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text(book.title, 0, 180, {
        align: "center",
        width: pageWidth,
      });

    doc
      .fontSize(18)
      .font("Helvetica")
      .fillColor("#4a4a6a")
      .text("Word Search Puzzle Book", 0, 240, {
        align: "center",
        width: pageWidth,
      });

    const lineX = pageWidth / 2 - 100;
    doc
      .moveTo(lineX, 280)
      .lineTo(lineX + 200, 280)
      .strokeColor("#4a4a6a")
      .lineWidth(2)
      .stroke();

    const detailsY = 320;
    doc
      .fontSize(12)
      .font("Helvetica")
      .fillColor("#666")
      .text(`Theme: ${book.theme}`, 0, detailsY, {
        align: "center",
        width: pageWidth,
      });
    doc
      .fontSize(12)
      .text(`Audience: ${book.targetAudience || "General"}`, 0, detailsY + 25, {
        align: "center",
        width: pageWidth,
      });
    doc
      .fontSize(12)
      .text(
        `Difficulty: ${book.difficultyLevel || "Medium"}`,
        0,
        detailsY + 50,
        {
          align: "center",
          width: pageWidth,
        },
      );
    doc.fontSize(12).text(`Puzzles: ${book.puzzleCount}`, 0, detailsY + 75, {
      align: "center",
      width: pageWidth,
    });

    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#aaa")
      .text(
        `Generated by Puzzle Book Generator • ${new Date().getFullYear()}`,
        0,
        pageHeight - 50,
        {
          align: "center",
          width: pageWidth,
        },
      );
  }

  private static addPuzzlePage(
    doc: PDFKit.PDFDocument,
    bookPuzzle: any,
    displayNumber: number,
    opts: any,
  ): void {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = opts.margins.left || 72;

    const puzzle = bookPuzzle.puzzle;
    const puzzleData = puzzle.data as any;
    const grid = puzzleData?.grid || [];
    const words = puzzleData?.words || [];

    if (grid.length === 0) {
      doc.text("Puzzle data not available", margin, 100);
      return;
    }

    const gridSize = grid.length;

    // ============================================================
    // DRAW HEADER
    // ============================================================
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text(`Puzzle #${displayNumber}`, margin, margin - 20);

    // ============================================================
    // DRAW WORDS LIST (top of page)
    // ============================================================
    let yPos = margin + 20;
    const wordsPerColumn = Math.min(3, Math.ceil(words.length / 6));
    const columnWidth = (pageWidth - margin * 2) / wordsPerColumn;

    doc
      .fontSize(9)
      .font("Helvetica-Bold")
      .fillColor("#333")
      .text("Words:", margin, yPos);
    yPos += 14;

    for (let i = 0; i < words.length; i++) {
      const col = i % wordsPerColumn;
      const row = Math.floor(i / wordsPerColumn);
      const x = margin + col * columnWidth;
      const y = yPos + row * 13;

      doc
        .fontSize(8)
        .font("Helvetica")
        .fillColor("#444")
        .text(`${i + 1}. ${words[i]}`, x, y, {
          width: columnWidth - 5,
          ellipsis: true,
        });
    }

    const totalRows = Math.ceil(words.length / wordsPerColumn);
    const wordsListHeight = totalRows * 13 + 10;
    yPos += wordsListHeight + 10;

    // ============================================================
    // GRID CALCULATION (with labels)
    // ============================================================
    const labelSize = 16;

    const availableWidth = pageWidth - margin * 2;
    const availableHeight = pageHeight - yPos - margin;

    const cellSizeFromWidth = (availableWidth - labelSize) / gridSize;
    const cellSizeFromHeight = (availableHeight - labelSize) / gridSize;

    let cellSize = Math.min(cellSizeFromWidth, cellSizeFromHeight);
    cellSize = Math.min(cellSize, 22);
    cellSize = Math.max(cellSize, 8);

    const finalTotalWidth = labelSize + gridSize * cellSize;
    const finalTotalHeight = labelSize + gridSize * cellSize;

    const gridStartX = (pageWidth - finalTotalWidth) / 2;
    const gridStartY = yPos;

    // ============================================================
    // DRAW GRID WITH LABELS
    // ============================================================
    this.drawGridWithLabels(
      doc,
      grid,
      gridSize,
      gridStartX,
      gridStartY,
      cellSize,
      labelSize,
    );
  }

  private static drawGridWithLabels(
    doc: PDFKit.PDFDocument,
    grid: string[][],
    gridSize: number,
    startX: number,
    startY: number,
    cellSize: number,
    labelSize: number,
  ): void {
    const labelFontSize = Math.min(9, cellSize * 0.45);

    // ============================================================
    // COLUMN LABELS (numbers at top)
    // ============================================================
    doc
      .rect(startX + labelSize, startY, gridSize * cellSize, labelSize)
      .fill("#e8e8e8");

    doc
      .rect(startX + labelSize, startY, gridSize * cellSize, labelSize)
      .strokeColor("#cccccc")
      .lineWidth(0.5)
      .stroke();

    doc.fontSize(labelFontSize).font("Helvetica-Bold").fillColor("#333333");

    for (let c = 0; c < gridSize; c++) {
      const x = startX + labelSize + c * cellSize;
      const y = startY;
      const labelText = String(c + 1);

      const textWidth = doc.widthOfString(labelText);
      const textHeight = doc.currentLineHeight(true);
      const textX = x + (cellSize - textWidth) / 2;
      const textY = y + (labelSize - textHeight) / 2;

      doc.text(labelText, textX, textY, {
        width: textWidth,
        height: textHeight,
        align: "center",
        lineBreak: false,
      });
    }

    // ============================================================
    // ROW LABELS (letters on left)
    // ============================================================
    doc
      .rect(startX, startY + labelSize, labelSize, gridSize * cellSize)
      .fill("#e8e8e8");

    doc
      .rect(startX, startY + labelSize, labelSize, gridSize * cellSize)
      .strokeColor("#cccccc")
      .lineWidth(0.5)
      .stroke();

    doc.fontSize(labelFontSize).font("Helvetica-Bold").fillColor("#333333");

    for (let r = 0; r < gridSize; r++) {
      const x = startX;
      const y = startY + labelSize + r * cellSize;
      const labelText = String.fromCharCode(65 + r);

      const textWidth = doc.widthOfString(labelText);
      const textHeight = doc.currentLineHeight(true);
      const textX = x + (labelSize - textWidth) / 2;
      const textY = y + (cellSize - textHeight) / 2;

      doc.text(labelText, textX, textY, {
        width: textWidth,
        height: textHeight,
        align: "center",
        lineBreak: false,
      });
    }

    // ============================================================
    // GRID CELLS
    // ============================================================
    for (let r = 0; r < gridSize; r++) {
      for (let c = 0; c < gridSize; c++) {
        const x = startX + labelSize + c * cellSize;
        const y = startY + labelSize + r * cellSize;
        const cell = grid[r]?.[c] || "";

        const isDark = (r + c) % 2 === 0;
        doc.rect(x, y, cellSize, cellSize).fill(isDark ? "#fafafa" : "#f0f0f0");

        doc
          .rect(x, y, cellSize, cellSize)
          .strokeColor("#d0d0d0")
          .lineWidth(0.5)
          .stroke();

        if (cell) {
          const fontSize = Math.min(12, cellSize * 0.5);
          doc.fontSize(fontSize).font("Helvetica-Bold").fillColor("#333");

          const textWidth = doc.widthOfString(cell);
          const textHeight = doc.currentLineHeight(true);
          const textX = x + (cellSize - textWidth) / 2;
          const textY = y + (cellSize - textHeight) / 2;

          doc.text(cell, textX, textY, {
            width: textWidth,
            height: textHeight,
            align: "center",
            lineBreak: false,
          });
        }
      }
    }

    // Border around entire grid
    const totalWidth = labelSize + gridSize * cellSize;
    const totalHeight = labelSize + gridSize * cellSize;

    doc
      .rect(startX, startY, totalWidth, totalHeight)
      .strokeColor("#999999")
      .lineWidth(1)
      .stroke();
  }

  private static addSolutionsPage(
    doc: PDFKit.PDFDocument,
    bookPuzzles: any[],
  ): void {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = 72;

    // ============================================================
    // SOLUTIONS HEADER
    // ============================================================
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text("Solutions", 0, 50, {
        align: "center",
        width: pageWidth,
      });

    const lineX = pageWidth / 2 - 60;
    doc
      .moveTo(lineX, 75)
      .lineTo(lineX + 120, 75)
      .strokeColor("#4a4a6a")
      .lineWidth(1)
      .stroke();

    let y = 100;

    // ✅ ARROW ICONS based on direction vector
    function getDirectionArrow(dr: number, dc: number): string {
      if (dr === 0 && dc > 0) return "→";
      else if (dr === 0 && dc < 0) return "←";
      else if (dr > 0 && dc === 0) return "↓";
      else if (dr < 0 && dc === 0) return "↑";
      else if (dr > 0 && dc > 0) return "↘";
      else if (dr < 0 && dc < 0) return "↖";
      else if (dr > 0 && dc < 0) return "↙";
      else if (dr < 0 && dc > 0) return "↗";
      return "→";
    }

    const wordFontSize = 8;
    const coordFontSize = 9;
    const rowHeight = 16;
    const headerHeight = 22;

    for (const bookPuzzle of bookPuzzles) {
      const puzzle = bookPuzzle.puzzle;
      const puzzleData = puzzle.data as any;
      const words = puzzleData?.words || [];

      // ✅ Use placedWords directly - this has the correct direction vectors!
      const placedWords = puzzleData?.placedWords || [];

      // Check if we need a new page
      const wordsHeight = Math.ceil(words.length / 2) * rowHeight;
      if (y + headerHeight + wordsHeight + 10 > pageHeight - 40) {
        doc.addPage();
        y = 50;
      }

      // Puzzle header
      doc
        .fontSize(11)
        .font("Helvetica-Bold")
        .fillColor("#333")
        .text(`Puzzle ${bookPuzzle.displayNumber}`, margin, y);
      y += headerHeight;

      // ✅ Build word map from placedWords (with correct dr, dc)
      const wordMap: Record<string, any> = {};

      for (const pw of placedWords) {
        const word = pw.word || "";
        if (word) {
          // ✅ Get direction vector from placedWords (NOT from solution)
          const dr = pw.direction?.dr ?? pw.dr ?? 0;
          const dc = pw.direction?.dc ?? pw.dc ?? 1;
          const startRow = pw.startRow ?? pw.row ?? 0;
          const startCol = pw.startCol ?? pw.col ?? 0;
          const wordLen = word.length;

          wordMap[word] = {
            startRow: startRow,
            startCol: startCol,
            endRow: startRow + dr * (wordLen - 1),
            endCol: startCol + dc * (wordLen - 1),
            dr: dr,
            dc: dc,
          };
        }
      }

      // ✅ 2-COLUMN LAYOUT
      const halfWords = Math.ceil(words.length / 2);
      const col1Width = (pageWidth - margin * 2) / 2 - 10;

      for (let i = 0; i < words.length; i++) {
        const word = words[i];
        const info = wordMap[word];
        const isRightColumn = i >= halfWords;
        const displayIndex = isRightColumn ? i - halfWords : i;

        const colX = isRightColumn ? margin + col1Width + 15 : margin + 5;
        const rowY = y + displayIndex * rowHeight;

        if (rowY + rowHeight > pageHeight - 30) {
          doc.addPage();
          y = 50;
          doc
            .fontSize(11)
            .font("Helvetica-Bold")
            .fillColor("#333")
            .text(`Puzzle ${bookPuzzle.displayNumber} (cont.)`, margin, y);
          y += headerHeight;
          const newRowY = y + displayIndex * rowHeight;
          if (newRowY + rowHeight > pageHeight - 30) {
            continue;
          }
        }

        // ✅ Format coordinate: K3 - L4 → (with arrow icon)
        let coordText = "";
        if (info && info.dr !== undefined && info.dc !== undefined) {
          const startLetter = String.fromCharCode(65 + (info.startRow ?? 0));
          const endLetter = String.fromCharCode(
            65 + (info.endRow ?? info.startRow ?? 0),
          );
          const startNum = (info.startCol ?? 0) + 1;
          const endNum = (info.endCol ?? info.startCol ?? 0) + 1;
          const arrow = getDirectionArrow(info.dr, info.dc);

          // ✅ Use proper arrow (→, ←, ↓, ↑, ↘, ↖, ↙, ↗)
          coordText = `${startLetter}${startNum} → ${endLetter}${endNum} ${arrow}`;
        } else {
          coordText = `${word} →`;
        }

        // ✅ Draw word
        const wordText = `${i + 1}. ${word}`;
        doc
          .fontSize(wordFontSize)
          .font("Helvetica-Bold")
          .fillColor("#333")
          .text(wordText, colX, rowY, {
            width: col1Width - 10,
            ellipsis: true,
          });

        // ✅ Draw coordinate with arrow icon
        const coordX = colX + 120;
        doc
          .fontSize(coordFontSize)
          .font("Helvetica")
          .fillColor("#666")
          .text(coordText, coordX, rowY + 1, {
            width: col1Width - 130,
            align: "left",
          });
      }

      const totalRows = Math.ceil(words.length / 2);
      y += totalRows * rowHeight + 8;
    }
  }

  private static drawDecorativeBorder(
    doc: PDFKit.PDFDocument,
    width: number,
    height: number,
  ): void {
    const padding = 40;
    const cornerRadius = 10;
    const x = padding;
    const y = padding;
    const w = width - padding * 2;
    const h = height - padding * 2;

    doc
      .roundedRect(x, y, w, h, cornerRadius)
      .strokeColor("#e0e0e0")
      .lineWidth(1)
      .stroke();

    const innerPadding = 15;
    doc
      .roundedRect(
        x + innerPadding,
        y + innerPadding,
        w - innerPadding * 2,
        h - innerPadding * 2,
        cornerRadius / 2,
      )
      .strokeColor("#e8e8e8")
      .lineWidth(0.5)
      .dash(4, { space: 4 })
      .stroke();
    doc.undash();

    const corners = [
      [x + innerPadding, y + innerPadding],
      [x + w - innerPadding, y + innerPadding],
      [x + innerPadding, y + h - innerPadding],
      [x + w - innerPadding, y + h - innerPadding],
    ];

    for (const [cx, cy] of corners) {
      doc.circle(cx, cy, 3).fill("#d0d0d0").stroke();
    }
  }
}
