import PDFDocument from "pdfkit";
import { prisma } from "@/lib/prisma";

export interface PDFOptions {
  pageSize?: "A4" | "Letter";
  includeSolutions?: boolean;
  solutionPlacement?: "back" | "after";
  fontSize?: number;
  fontName?: string;
  margins?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
}

export interface PDFResult {
  buffer: Buffer;
  pageCount: number;
}

export class PDFGenerator {
  private static readonly DEFAULT_OPTIONS: Required<
    Omit<PDFOptions, "margins">
  > & {
    margins: Required<NonNullable<PDFOptions["margins"]>>;
  } = {
    pageSize: "A4",
    includeSolutions: true,
    solutionPlacement: "back",
    fontSize: 10,
    fontName: "Helvetica",
    margins: {
      top: 72,
      bottom: 72,
      left: 72,
      right: 72,
    },
  };

  static async generateBookPDF(
    bookId: string,
    options: PDFOptions = {},
  ): Promise<PDFResult> {
    const opts = {
      ...this.DEFAULT_OPTIONS,
      ...options,
      margins: {
        ...this.DEFAULT_OPTIONS.margins,
        ...(options.margins ?? {}),
      },
    };

    const book = await prisma.book.findUnique({
      where: { id: bookId },
      include: {
        bookPuzzles: {
          include: {
            puzzle: true,
            puzzleVersion: true,
            solution: true,
          },
          orderBy: {
            position: "asc",
          },
        },
      },
    });

    if (!book) {
      throw new Error("Book not found");
    }

    const doc = new PDFDocument({
      size: opts.pageSize === "A4" ? "A4" : "LETTER",
      margins: opts.margins,
      autoFirstPage: true,
      info: {
        Title: book.title,
        Author: "Puzzle Book Generator",
        Subject: `${book.puzzleCount} Word Search Puzzles`,
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));

    let pageCount = 0;

    // Cover Page
    pageCount++;
    this.addCoverPage(doc, book);

    // Each puzzle on its own page
    for (const bookPuzzle of book.bookPuzzles) {
      pageCount++;
      doc.addPage();
      this.addPuzzlePage(doc, bookPuzzle, bookPuzzle.displayNumber, opts);
    }

    // Solutions at the back
    if (opts.includeSolutions && opts.solutionPlacement === "back") {
      pageCount++;
      doc.addPage();
      this.addSolutionsPage(doc, book.bookPuzzles);
    }

    doc.end();

    return new Promise((resolve) => {
      doc.on("end", () => {
        const buffer = Buffer.concat(chunks);
        resolve({ buffer, pageCount });
      });
    });
  }

  private static addCoverPage(doc: PDFKit.PDFDocument, book: any): void {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;

    this.drawDecorativeBorder(doc, pageWidth, pageHeight);

    doc
      .fontSize(36)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text(book.title, 0, 180, {
        align: "center",
        width: pageWidth,
      });

    doc
      .fontSize(18)
      .font("Helvetica")
      .fillColor("#4a4a6a")
      .text("Word Search Puzzle Book", 0, 240, {
        align: "center",
        width: pageWidth,
      });

    const lineX = pageWidth / 2 - 100;
    doc
      .moveTo(lineX, 280)
      .lineTo(lineX + 200, 280)
      .strokeColor("#4a4a6a")
      .lineWidth(2)
      .stroke();

    const detailsY = 320;
    doc
      .fontSize(12)
      .font("Helvetica")
      .fillColor("#666")
      .text(`Theme: ${book.theme}`, 0, detailsY, {
        align: "center",
        width: pageWidth,
      });
    doc
      .fontSize(12)
      .text(`Audience: ${book.targetAudience || "General"}`, 0, detailsY + 25, {
        align: "center",
        width: pageWidth,
      });
    doc
      .fontSize(12)
      .text(
        `Difficulty: ${book.difficultyLevel || "Medium"}`,
        0,
        detailsY + 50,
        {
          align: "center",
          width: pageWidth,
        },
      );
    doc.fontSize(12).text(`Puzzles: ${book.puzzleCount}`, 0, detailsY + 75, {
      align: "center",
      width: pageWidth,
    });

    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#aaa")
      .text(
        `Generated by Puzzle Book Generator • ${new Date().getFullYear()}`,
        0,
        pageHeight - 50,
        {
          align: "center",
          width: pageWidth,
        },
      );
  }

  private static addPuzzlePage(
    doc: PDFKit.PDFDocument,
    bookPuzzle: any,
    displayNumber: number,
    opts: any,
  ): void {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = opts.margins.left || 72;

    const puzzle = bookPuzzle.puzzle;
    const puzzleData = puzzle.data as any;
    const grid = puzzleData?.grid || [];
    const words = puzzleData?.words || [];

    if (grid.length === 0) {
      doc.text("Puzzle data not available", margin, 100);
      return;
    }

    const gridSize = grid.length;

    // Puzzle Number
    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text(`Puzzle #${displayNumber}`, margin, 50);

    // Difficulty badge
    const difficulty = puzzle.difficultyLabel || puzzle.difficulty || "Medium";
    const badgeColors: Record<string, string> = {
      Easy: "#4CAF50",
      Medium: "#FF9800",
      Hard: "#F44336",
      Expert: "#9C27B0",
    };
    const badgeColor = badgeColors[difficulty] || "#666";

    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .fillColor("white")
      .rect(pageWidth - margin - 80, 45, 70, 22)
      .fill(badgeColor);

    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .fillColor("white")
      .text(difficulty, pageWidth - margin - 45, 50, {
        width: 30,
        align: "center",
      });

    // Words List
    const wordListY = 85;
    doc
      .fontSize(11)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text("Words to Find:", margin, wordListY);

    let numColumns = 3;
    if (gridSize >= 15) numColumns = 4;
    if (gridSize >= 18) numColumns = 4;
    if (words.length > 30) numColumns = 4;
    if (words.length < 12) numColumns = 2;

    const wordStartY = wordListY + 20;
    const wordsPerColumn = Math.ceil(words.length / numColumns);
    const columnWidth =
      (pageWidth - margin * 2 - (numColumns - 1) * 15) / numColumns;

    for (let i = 0; i < words.length; i++) {
      const col = Math.floor(i / wordsPerColumn);
      const row = i % wordsPerColumn;
      const x = margin + col * (columnWidth + 15);
      const y = wordStartY + row * 18;

      let displayWord = words[i];
      if (displayWord.length > 18) {
        displayWord = displayWord.substring(0, 15) + "...";
      }

      doc
        .fontSize(9)
        .font("Helvetica")
        .fillColor("#444")
        .text(`${i + 1}. ${displayWord}`, x, y, {
          width: columnWidth - 10,
        });
    }

    const totalWordRows = Math.ceil(words.length / numColumns);
    const wordListHeight = totalWordRows * 18 + 15;
    let gridStartY = wordStartY + wordListHeight + 15;

    const availableHeight = pageHeight - gridStartY - 50;
    const availableWidth = pageWidth - margin * 2 - 20;

    let cellSize = Math.min(
      availableWidth / gridSize,
      availableHeight / gridSize,
    );

    if (cellSize < 18) {
      const reducedHeight =
        wordStartY + Math.ceil(words.length / numColumns) * 14 + 10;
      gridStartY = reducedHeight;
      const newAvailableHeight = pageHeight - gridStartY - 50;
      cellSize = Math.min(
        availableWidth / gridSize,
        newAvailableHeight / gridSize,
      );
    }

    cellSize = Math.max(cellSize, 14);

    // ============================================================
    // GRID WITH LABELS
    // ============================================================
    const labelWidth = 24;
    const labelHeight = 24;
    const totalGridWidth = cellSize * gridSize + labelWidth;
    const totalGridHeight = cellSize * gridSize + labelHeight;
    const gridStartX = (pageWidth - totalGridWidth) / 2;
    const gridStartYFinal = gridStartY;

    // Top row background
    doc
      .rect(
        gridStartX + labelWidth,
        gridStartYFinal,
        cellSize * gridSize,
        labelHeight,
      )
      .fill("#f5f5f5");

    // Left column background
    doc
      .rect(
        gridStartX,
        gridStartYFinal + labelHeight,
        labelWidth,
        cellSize * gridSize,
      )
      .fill("#f5f5f5");

    // Column labels (numbers)
    // Column labels (numbers)
    doc.fontSize(9).font("Helvetica-Bold").fillColor("#666");

    for (let c = 0; c < gridSize; c++) {
      const x = gridStartX + labelWidth + c * cellSize;
      const y = gridStartYFinal;
      const labelText = String(c + 1);

      const textWidth = doc.widthOfString(labelText);
      const textHeight = doc.currentLineHeight(true);

      const textX = x + (cellSize - textWidth) / 2;
      const textY = y + (labelHeight - textHeight) / 2;

      doc.text(labelText, textX, textY, {
        width: textWidth,
        height: textHeight,
        align: "center",
        lineBreak: false,
      });
    }

    // Row labels (letters)
    doc.fontSize(9).font("Helvetica-Bold").fillColor("#666");

    for (let r = 0; r < gridSize; r++) {
      const x = gridStartX;
      const y = gridStartYFinal + labelHeight + r * cellSize;
      const letter = String.fromCharCode(65 + r);

      const textHeight = doc.currentLineHeight(true);

      // Full row-label cell
      const textY = y + (cellSize - textHeight) / 2;

      doc.text(letter, x, textY, {
        width: labelWidth,
        height: textHeight,
        align: "center",
        lineBreak: false,
      });
    }

    // ============================================================
    // DRAW GRID CELLS - PERFECTLY CENTERED
    // ============================================================
    for (let r = 0; r < gridSize; r++) {
      for (let c = 0; c < gridSize; c++) {
        const x = gridStartX + labelWidth + c * cellSize;
        const y = gridStartYFinal + labelHeight + r * cellSize;
        const cell = grid[r]?.[c] || "";

        const isDark = (r + c) % 2 === 0;
        doc.rect(x, y, cellSize, cellSize).fill(isDark ? "#fafafa" : "#f0f0f0");

        doc
          .rect(x, y, cellSize, cellSize)
          .strokeColor("#d0d0d0")
          .lineWidth(0.5)
          .stroke();

        if (cell) {
          const fontSize = Math.min(16, cellSize * 0.5);

          doc.fontSize(fontSize).font("Helvetica-Bold").fillColor("#333");

          const textWidth = doc.widthOfString(cell);
          const textHeight = doc.currentLineHeight(true);

          const textX = x + (cellSize - textWidth) / 2;
          const textY = y + (cellSize - textHeight) / 2;

          doc.text(cell, textX, textY, {
            width: textWidth,
            height: textHeight,
            align: "center",
            lineBreak: false,
          });
        }
      }
    }

    // Footer
    doc
      .fontSize(8)
      .font("Helvetica")
      .fillColor("#aaa")
      .text(`Puzzle #${displayNumber}`, margin, pageHeight - 30, {
        width: pageWidth - margin * 2,
        align: "center",
      });
  }

  private static addSolutionsPage(
    doc: PDFKit.PDFDocument,
    bookPuzzles: any[],
  ): void {
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const margin = 72;

    doc
      .fontSize(28)
      .font("Helvetica-Bold")
      .fillColor("#1a1a2e")
      .text("Solutions", 0, 60, {
        align: "center",
        width: pageWidth,
      });

    doc
      .fontSize(12)
      .font("Helvetica")
      .fillColor("#666")
      .text("Answer key with word positions", 0, 100, {
        align: "center",
        width: pageWidth,
      });

    const lineX = pageWidth / 2 - 80;
    doc
      .moveTo(lineX, 120)
      .lineTo(lineX + 160, 120)
      .strokeColor("#4a4a6a")
      .lineWidth(1)
      .stroke();

    let y = 160;

    function getDirectionText(dr: number, dc: number): string {
      if (dr === 0 && dc > 0) return "Right";
      else if (dr === 0 && dc < 0) return "Left";
      else if (dr > 0 && dc === 0) return "Down";
      else if (dr < 0 && dc === 0) return "Up";
      else if (dr > 0 && dc > 0) return "Down-Right";
      else if (dr < 0 && dc < 0) return "Up-Left";
      else if (dr > 0 && dc < 0) return "Down-Left";
      else if (dr < 0 && dc > 0) return "Up-Right";
      return "";
    }

    for (const bookPuzzle of bookPuzzles) {
      const puzzle = bookPuzzle.puzzle;
      const puzzleData = puzzle.data as any;
      const words = puzzleData?.words || [];
      const solution = bookPuzzle.solution?.data as any;
      const solutionWords = solution?.words || [];

      if (y + 80 > pageHeight - 40) {
        doc.addPage();
        y = 60;
      }

      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .fillColor("#1a1a2e")
        .text(`Puzzle ${bookPuzzle.displayNumber}`, margin, y);
      y += 25;

      const wordMap: Record<string, any> = {};

      for (const item of solutionWords) {
        if (typeof item === "string") {
          wordMap[item] = null;
        } else if (item && typeof item === "object") {
          const word = item.word || item.Word || item.text || "";
          if (word) {
            wordMap[word] = {
              startRow: item.startRow ?? item.startCol ?? 0,
              startCol: item.startCol ?? 0,
              endRow: item.endRow ?? item.startRow ?? 0,
              endCol: item.endCol ?? item.startCol ?? 0,
              direction: item.direction || "",
            };
          }
        }
      }

      if (Object.keys(wordMap).length === 0) {
        for (let i = 0; i < words.length && i < solutionWords.length; i++) {
          const word = words[i];
          const item = solutionWords[i];
          if (typeof item === "object" && item !== null) {
            wordMap[word] = {
              startRow: item.startRow ?? 0,
              startCol: item.startCol ?? 0,
              endRow: item.endRow ?? item.startRow ?? 0,
              endCol: item.endCol ?? item.startCol ?? 0,
              direction: item.direction || "",
            };
          } else {
            wordMap[word] = null;
          }
        }
      }

      for (let i = 0; i < words.length; i++) {
        const word = words[i];
        const info = wordMap[word];

        if (y > pageHeight - 40) {
          doc.addPage();
          y = 60;
          doc
            .fontSize(16)
            .font("Helvetica-Bold")
            .fillColor("#1a1a2e")
            .text(`Puzzle ${bookPuzzle.displayNumber} (cont.)`, margin, y);
          y += 25;
        }

        let coordText = "";
        if (info) {
          const startRow = info.startRow ?? 0;
          const startCol = info.startCol ?? 0;
          const endRow = info.endRow ?? startRow;
          const endCol = info.endCol ?? startCol;

          const startLetter = String.fromCharCode(65 + startRow);
          const endLetter = String.fromCharCode(65 + endRow);
          const startNum = startCol + 1;
          const endNum = endCol + 1;

          const dr = endRow - startRow;
          const dc = endCol - startCol;
          const direction = getDirectionText(dr, dc);

          coordText = `${startLetter}${startNum} → ${endLetter}${endNum} (${direction})`;
        } else {
          coordText = "—";
        }

        if (i % 2 === 0) {
          doc.rect(margin, y - 3, pageWidth - margin * 2, 20).fill("#f8f8f8");
        }

        doc
          .fontSize(10)
          .font(i % 2 === 0 ? "Helvetica-Bold" : "Helvetica")
          .fillColor("#333")
          .text(`${i + 1}. ${word}`, margin + 10, y);

        doc
          .fontSize(9)
          .font("Helvetica")
          .fillColor("#666")
          .text(coordText, margin + 250, y);

        y += 22;
      }

      y += 15;
    }
  }

  private static drawDecorativeBorder(
    doc: PDFKit.PDFDocument,
    width: number,
    height: number,
  ): void {
    const padding = 40;
    const cornerRadius = 10;
    const x = padding;
    const y = padding;
    const w = width - padding * 2;
    const h = height - padding * 2;

    doc
      .roundedRect(x, y, w, h, cornerRadius)
      .strokeColor("#e0e0e0")
      .lineWidth(1)
      .stroke();

    const innerPadding = 15;
    doc
      .roundedRect(
        x + innerPadding,
        y + innerPadding,
        w - innerPadding * 2,
        h - innerPadding * 2,
        cornerRadius / 2,
      )
      .strokeColor("#e8e8e8")
      .lineWidth(0.5)
      .dash(4, { space: 4 })
      .stroke();
    doc.undash();

    const corners = [
      [x + innerPadding, y + innerPadding],
      [x + w - innerPadding, y + innerPadding],
      [x + innerPadding, y + h - innerPadding],
      [x + w - innerPadding, y + h - innerPadding],
    ];

    for (const [cx, cy] of corners) {
      doc.circle(cx, cy, 3).fill("#d0d0d0").stroke();
    }
  }
}
