export const foodWords = [
  // Italian
  'PIZZA', 'PASTA', 'LASAGNA', 'SPAGHETTI', 'FETTUCCINE',
  'GNOCCHI', 'RISOTTO', 'BRUSCHETTA', 'CANNOLI', 'GELATO',
  // Mexican
  'TACO', 'BURRITO', 'QUESADILLA', 'ENCHILADA', 'FAJITA',
  'CHIMICHANGA', 'TAMALE', 'POZOLE', 'CHURRO', 'SALSA',
  // American
  'BURGER', 'SANDWICH', 'FRENCHFRIES', 'MACARONI', 'CHEESE',
  'STEAK', 'ROAST', 'GRILLED', 'SMOKED', 'BARBECUE',
  // Asian
  'SUSHI', 'RAMEN', 'DUMPLING', 'SPRINGROLL', 'FRIEDRICE',
  'TEMPURA', 'TERIYAKI', 'WASABI', 'MISO', 'EDAMAME',
  // Desserts
  'CAKE', 'COOKIE', 'PIE', 'BROWNIE', 'CUPCAKE',
  'DONUT', 'MUFFIN', 'SCONE', 'CROISSANT', 'BREAD',
  'ICE CREAM', 'PUDDING', 'MOUSSE', 'TIRAMISU', 'CHEESECAKE',
  // Ingredients
  'CHOCOLATE', 'VANILLA', 'STRAWBERRY', 'LEMON', 'ORANGE',
  'GINGER', 'GARLIC', 'ONION', 'TOMATO', 'PEPPER',
  'OREGANO', 'BASIL', 'CINNAMON', 'NUTMEG', 'CUMIN'
];