export const spaceWords = [
  // Planets and Celestial Bodies
  'MERCURY', 'VENUS', 'EARTH', 'MARS', 'JUPITER',
  'SATURN', 'URANUS', 'NEPTUNE', 'PLUTO', 'MOON',
  'SUN', 'STAR', 'GALAXY', 'NEBULA', 'COMET',
  'ASTEROID', 'METEOR', 'PLANET', 'ORBIT', 'SATELLITE',
  'ASTRONAUT', 'ROCKET', 'SPACESHIP', 'TELESCOPE', 'OBSERVATORY',
  'GRAVITY', 'ATMOSPHERE', 'ECLIPSE', 'SUPERNOVA', 'QUASAR',
  'PULSAR', 'BLACKHOLE', 'WORMHOLE', 'COSMOS', 'UNIVERSE',
  'CONSTELLATION', 'ANDROMEDA', 'ORION', 'CASSIOPEIA', 'DRACO',
  'PEGASUS', 'HERCULES', 'LEO', 'VIRGO', 'SAGITTARIUS',
  'SCORPIUS', 'TAURUS', 'GEMINI', 'CANCER', 'AQUARIUS',
  'PISCES', 'ARIES', 'LIBRA', 'CAPRICORN', 'PHOENIX'
];