// src/modules/themes/word-lists/space.ts
export const spaceWords = {
  simple: [
    // Planets
    "MERCURY",
    "VENUS",
    "EARTH",
    "MARS",
    "JUPITER",
    "SATURN",
    "URANUS",
    "NEPTUNE",
    "PLUTO",
    "MOON",
    "SUN",
    "STAR",
    "PLANET",
    "COMET",
    "ASTEROID",
    "METEOR",
    "GALAXY",
    "NEBULA",
    "QUASAR",
    "PULSAR",

    // Space terms
    "ROCKET",
    "SPACE",
    "SHUTTLE",
    "SATELLITE",
    "ASTRONAUT",
    "COSMONAUT",
    "MISSION",
    "LAUNCH",
    "ORBIT",
    "CRATER",
    "GRAVITY",
    "SOLAR",
    "SYSTEM",
    "COSMOS",
    "UNIVERSE",
    "ECLIPSE",
    "LIGHT",
    "DARK",
    "VOID",
    "GAS",

    // Space objects
    "STAR",
    "MOON",
    "SUN",
    "COMET",
    "METEOR",
    "ASTEROID",
    "PLANET",
    "ORBIT",
    "RINGS",
    "SURFACE",
    "ATMOSPHERE",
    "CLOUDS",
    "STORMS",
    "HEAT",
    "COLD",
    "ICE",
    "WATER",
    "ROCK",
    "DUST",
    "GAS",

    // Astronauts - simple
    "ARMSTRONG",
    "ALDRIN",
    "COLLINS",
    "GAGARIN",
    "TERESHKOVA",
    "RIDE",
    "JEMISON",
    "GLENN",
    "SHEPARD",
    "GRISSOM",
    "CHAWLA",
    "HUSBAND",
    "RESNIK",
    "MCNIAR",
    "FRANKLIN",
    "WALZ",
    "PETERSON",
    "SMITH",
    "JONES",
    "DAVIS",

    // Space agencies
    "NASA",
    "ESA",
    "ROSCOSMOS",
    "JAXA",
    "ISRO",
    "CNSA",
    "UKSA",
    "DLR",
    "CNES",
    "ASI",

    // Space missions - simple
    "APOLLO",
    "GEMINI",
    "MERCURY",
    "VOSTOK",
    "VOSKHOD",
    "SOYUZ",
    "SALYUT",
    "SKYLAB",
    "MIR",
    "ISS",

    // Spacecraft - simple
    "VOYAGER",
    "PIONEER",
    "MARINER",
    "VIKING",
    "PATHFINDER",
    "OPPORTUNITY",
    "SPIRIT",
    "CURIOSITY",
    "PERSEVERANCE",
    "INGENUITY",

    // Constellations - simple
    "ORION",
    "BIG DIPPER",
    "LITTLE DIPPER",
    "CASSIOPEIA",
    "ANDROMEDA",
    "PEGASUS",
    "SCORPIUS",
    "LEO",
    "DRACO",
    "CYGNUS",

    // Telescope terms
    "LENS",
    "MIRROR",
    "EYEPIECE",
    "MOUNT",
    "TRIPOD",
    "FILTER",
    "FOCUS",
    "ZENITH",
    "HORIZON",
    "MERIDIAN",
  ],

  intermediate: [
    // Planets - full names
    "MERCURY",
    "VENUS",
    "EARTH",
    "MARS",
    "JUPITER",
    "SATURN",
    "URANUS",
    "NEPTUNE",
    "PLUTO",
    "CERES",
    "HAUMEA",
    "MAKEMAKE",
    "ERIS",
    "SEDNA",
    "GONG GONG",
    "QUAOAR",
    "VARUNA",
    "IKU TURSO",
    "PLUTINO",
    "CHARON",

    // Moons
    "PHOBOS",
    "DEIMOS",
    "IO",
    "EUROPA",
    "GANYMEDE",
    "CALLISTO",
    "TITAN",
    "ENCELADUS",
    "DIONE",
    "RHEA",
    "TETHYS",
    "IA PETUS",
    "MIMAS",
    "TRITON",
    "CHARON",
    "S/2004",
    "PROTEO",
    "NEREID",
    "LARISSA",
    "DESPINA",

    // Stars & Galaxies
    "SIRIUS",
    "CANOPUS",
    "ARCTURUS",
    "VEGA",
    "CAPELLA",
    "RIGEL",
    "PROCYON",
    "ALDEBARAN",
    "ALTAIR",
    "ANTARES",
    "SPICA",
    "POLARIS",
    "BETELGEUSE",
    "CRUX",
    "MILKY WAY",
    "ANDROMEDA",
    "TRIANGULUM",
    "CENTAURUS",
    "BODE'S",
    "CIGAR",

    // Space missions - intermediate
    "APOLLO 11",
    "APOLLO 13",
    "VOYAGER 1",
    "VOYAGER 2",
    "PIONEER 10",
    "PIONEER 11",
    "CASSINI HUYGENS",
    "GALILEO",
    "JUNO",
    "NEW HORIZONS",
    "VIKING 1",
    "VIKING 2",
    "SPIRIT",
    "OPPORTUNITY",
    "CURIOSITY",
    "PERSEVERANCE",
    "INGENUITY",
    "MARS EXPRESS",
    "MAVEN",
    "MANGALYAAN",
    "CHANDRA",
    "HUBBLE",
    "JAMES WEBB",
    "SPITZER",
    "FERMI",
    "XMM",
    "SWIFT",
    "SAX",
    "ROSAT",
    "XRISM",

    // Astronauts - intermediate
    "NEIL ARMSTRONG",
    "BUZZ ALDRIN",
    "YURI GAGARIN",
    "VALENTINA TERESHKOVA",
    "SALLY RIDE",
    "MAE JEMISON",
    "CHRISTA MCAULIFFE",
    "JUDITH RESNIK",
    "KALPANA CHAWLA",
    "RICK HUSBAND",
    "RONALD MCNAIR",
    "DICK SCOBEE",
    "ELLISON ONIZUKA",
    "CHRISTA MCAULIFFE",
    "ROBERT CRIPPEN",
    "DICK TRULY",
    "THOMAS STAFFORD",
    "JAMES IRWIN",
    "EDGAR MITCHELL",
    "CHARLIE DUKE",
    "HARRISON SCHMITT",
    "RALPH KOHN",
    "SUNITA WILLIAMS",
    "PEGGY WHITSON",

    // Space agencies - full
    "NASA",
    "ESA",
    "ROSCOSMOS",
    "JAXA",
    "ISRO",
    "CNSA",
    "UKSA",
    "DLR",
    "CNES",
    "ASI",
    "CSA",
    "AEB",
    "INPE",
    "SUPARCO",
    "KARI",
    "MOJ",
    "NSPO",
    "SBC",
    "NSO",
    "EO",

    // Telescopes - intermediate
    "HUBBLE",
    "WEBB",
    "CHANDRA",
    "SPITZER",
    "KEPLER",
    "TESS",
    "CHEOPS",
    "GAIA",
    "HERSCHEL",
    "PLANCK",
    "ALMA",
    "ARECIBO",
    "GREEN BANK",
    "FAST",
    "KEK",
    "VLT",
    "GEMINI",
    "SUBARU",
    "LBT",
    "MAGELLAN",

    // Space phenomena
    "SUPERNOVA",
    "BLACK HOLE",
    "NEUTRON STAR",
    "WHITE DWARF",
    "RED GIANT",
    "BLUE GIANT",
    "YELLOW DWARF",
    "BROWN DWARF",
    "GRAVITATIONAL WAVE",
    "SOLAR WIND",
    "COSMIC RAY",
    "GAMMA RAY",
    "X RAY",
    "ULTRAVIOLET",
    "INFRARED",
    "RADIO WAVE",
    "ECLIPSE",
    "SOLAR FLARE",
    "CORONA",
    "PROMINENCE",
    "SUNSPOT",
    "AURORA",
    "COMET TAIL",
    "METEOR SHOWER",

    // Spacecraft - intermediate
    "SOYUZ",
    "DRAGON",
    "STARLINER",
    "ORION",
    "SLS",
    "FALCON 9",
    "STARSHIP",
    "NEW GLENN",
    "VULCAN",
    "ARIANE",
    "PROTON",
    "LONG MARCH",
    "H2A",
    "PSLV",
    "GSLV",
    "ELECTRON",
    "LAUNCHER ONE",
    "MINOTAUR",
    "PEGASUS",
    "ANTARES",
  ],

  hard: [
    // Planets - Full Scientific
    "SOL",
    "LUNAR",
    "TERRA",
    "MARTIAN",
    "JOVIAN",
    "SATURNIAN",
    "URANIAN",
    "NEPTUNIAN",
    "PLUTONIAN",
    "CEREREAN",
    "TITANIAN",
    "EUROPEAN",
    "GANYMEDIAN",
    "CALLISTOAN",
    "TRITONIAN",
    "CHARONIAN",
    "SEDNOID",
    "HAUMEAN",
    "MAKEMAKEAN",
    "ERIDIAN",

    // Moons - Scientific
    "GALILEAN MOONS",
    "SHEPHERD MOONS",
    "CO ORBITAL",
    "TROJAN",
    "KIRKWOOD GAP",
    "EULER",
    "LAGRANGE",
    "LIBRATION",
    "RESONANCE",
    "ROTATION",
    "SYNCHRONOUS",
    "ASYNCHRONOUS",
    "RECOGNITION",
    "PHOBOS",
    "DEIMOS",
    "IO",
    "EUROPA",
    "GANYMEDE",
    "CALLISTO",
    "TITAN",
    "ENCELADUS",
    "DIONE",
    "RHEA",
    "TETHYS",
    "IAPETUS",
    "MIMAS",
    "TRITON",
    "CHARON",
    "PROTEUS",
    "NEREID",

    // Stars - Scientific
    "SPECTRAL TYPE",
    "MAIN SEQUENCE",
    "RED SUPERGIANT",
    "BLUE SUPERGIANT",
    "C VAR",
    "CEPHEID",
    "RR LYRAE",
    "BINARY",
    "MULTIPLE",
    "VARIABLE",
    "PULSAR",
    "MAGNETAR",
    "QUARK STAR",
    "PREON STAR",
    "ZPE",
    "PLANCK",
    "WIMPS",
    "MACHOS",
    "AXION",
    "STERILE",

    // Galaxies - Scientific
    "SPIRAL",
    "ELLIPTICAL",
    "IRREGULAR",
    "BARRED",
    "LENTICULAR",
    "ACTIVE",
    "SEYFERT",
    "BLAZAR",
    "QUASAR",
    "RADIO",
    "MAGNIFICENT",
    "THE WHEEL",
    "CARTWHEEL",
    "SOMBRERO",
    "WHIRLPOOL",
    "BLACK EYE",
    "SUNFLOWER",
    "TOOTHED",
    "HOAG'S",
    "BOOTE'S",

    // Space Phenomena - Scientific
    "GRAVITATIONAL LENSING",
    "MICROLENSING",
    "STRONG LENSING",
    "WEAK LENSING",
    "DARK MATTER",
    "DARK ENERGY",
    "VACUUM ENERGY",
    "QUINTESSENCE",
    "PHANTOM",
    "COSMIC INFLATION",
    "BIG BANG",
    "BIG BOUNCE",
    "BIG RIP",
    "BIG FREEZE",
    "HEAT DEATH",
    "GRAVITATIONAL COLLAPSE",
    "SPAGHETTIFICATION",
    "ACCELERATION",
    "DECELERATION",
    "RECOMBINATION",
    "REIONIZATION",
    "NUCLEOSYNTHESIS",
    "PRIMORDIAL",
    "CHIRP",
    "FOM",
    "SIGMA",
    "RAO",
    "GAL",
    "ISM",
    "AGN",

    // Space Missions - Advanced
    "MARS SAMPLE RETURN",
    "DRAGONFLY",
    "JUICE",
    "EUROPA CLIPPER",
    "DARTS",
    "LUCY",
    "PSYCHE",
    "SPHEREX",
    "GEO",
    "AXIS",
    "SOLAR ORBITER",
    "BEPICOLOMBO",
    "EXOMARS",
    "TRACE GAS",
    "ROSETTA",
    "PHILAE",
    "DAWN",
    "MESSENGER",
    "CASSINI",
    "HUYGENS",
    "UKube",
    "MOON",
    "LADEE",
    "GRAIL",
    "LRO",
    "LCROSS",
    "CHANDRAYAAN",
    "AL 1",
    "YOMI",
    "NOZOMI",

    // Telescopes - Advanced
    "SPHEREX",
    "EXPRESS",
    "HESS",
    "VERITAS",
    "HAWC",
    "CTA",
    "LIGO",
    "VIRGO",
    "KAGRA",
    "GEO600",
    "JWST",
    "CHANDRA",
    "XMM",
    "ASTROSAT",
    "NUSTAR",
    "SWIFT",
    "FERMI",
    "AGILE",
    "INTEGRAL",
    "EPIC",
    "NEOWISE",
    "WISE",
    "AKARI",
    "IRAS",
    "ISO",
    "HERSCHEL",
    "SOFIA",
    "TESS",
    "KEPLER",
    "COROT",

    // Astronauts - Advanced
    "PAVEL BELYAYEV",
    "VLADIMIR KOMAROV",
    "GEORGY DOBROVOLSKY",
    "VLADISLAV VOLKOV",
    "VIKTOR PATSAYEV",
    "ANATOLE ANTIPOV",
    "PYOTR KLIMUK",
    "NIKOLAI RUKAVISHNIKOV",
    "SIGMUND JAHN",
    "MIROSLAW HERMASZEWSKI",
    "VLADIMIR LYAKHOV",
    "LEONID POPOV",
    "VALERY RYUMIN",
    "DMITRI YUR",
    "KADER ABDEL",
    "HISHAM MOUR",
    "ANATOLY ARTSEBARSKY",
    "SERGEI KRIKALEV",
    "HELENA KARINA",
    "ULF MERBOLD",
    "JOHN FABIAN",
    "KAREN NYBERG",
    "MARY CLEAVE",
    "ANNA FISHER",
    "DIANE BUCK",
    "RHODA JONES",
    "TERESA MOORE",
    "JOSEPH ALLEN",
    "JOSEPH TANNER",
    "JOSEPH EDWARDS",
    "KEVIN DAVIS",
    "KEVIN NORRIS",

    // Space Agencies - Full
    "NATIONAL AERONAUTICS AND SPACE ADMINISTRATION",
    "EUROPEAN SPACE AGENCY",
    "RUSSIAN STATE CORPORATION FOR SPACE ACTIVITIES",
    "JAPAN AEROSPACE EXPLORATION AGENCY",
    "INDIAN SPACE RESEARCH ORGANISATION",
    "CHINA NATIONAL SPACE ADMINISTRATION",
    "UK SPACE AGENCY",
    "GERMAN AEROSPACE CENTER",
    "NATIONAL CENTRE FOR SPACE STUDIES",
    "ITALIAN SPACE AGENCY",
    "CANADIAN SPACE AGENCY",
    "BRAZILIAN SPACE AGENCY",
    "UKRAINIAN STATE SPACE AGENCY",
    "PAKISTAN SPACE AND UPPER ATMOSPHERE RESEARCH COMMISSION",
    "SOUTH AFRICAN NATIONAL SPACE AGENCY",
    "ISRAEL SPACE AGENCY",
  ],
};
