// src/modules/themes/word-lists/technology.ts
export const technologyWords = {
  simple: [
    // Basic tech terms
    "COMPUTER",
    "LAPTOP",
    "TABLET",
    "PHONE",
    "MOBILE",
    "TECH",
    "APP",
    "SOFTWARE",
    "HARDWARE",
    "DEVICE",
    "SCREEN",
    "MOUSE",
    "KEYBOARD",
    "SPEAKER",
    "CAMERA",
    "PRINTER",
    "SCANNER",
    "DRIVE",
    "MEMORY",
    "CHIP",
    "BATTERY",
    "CHARGER",
    "CABLE",
    "WIRE",
    "BLUETOOTH",
    "WIFI",
    "INTERNET",
    "WEB",
    "SITE",
    "PAGE",
    "EMAIL",
    "TEXT",
    "VIDEO",
    "AUDIO",
    "PHOTO",
    "FILE",
    "FOLDER",
    "DOCUMENT",
    "SPREADSHEET",
    "PRESENTATION",

    // Programming basics
    "CODE",
    "PROGRAM",
    "APP",
    "GAME",
    "DATA",
    "CLOUD",
    "SERVER",
    "NETWORK",
    "SECURITY",
    "PASSWORD",
    "USER",
    "LOGIN",
    "SIGN",
    "CLICK",
    "DRAG",
    "DROP",
    "SCROLL",
    "ZOOM",
    "REFRESH",
    "BACKUP",

    // Web terms
    "GOOGLE",
    "YOUTUBE",
    "FACEBOOK",
    "INSTAGRAM",
    "TWITTER",
    "TIKTOK",
    "SNAPCHAT",
    "WHATSAPP",
    "MESSENGER",
    "TELEGRAM",
    "EMAIL",
    "SPAM",
    "PHISHING",
    "VIRUS",
    "MALWARE",
    "HACKER",
    "FIREWALL",
    "ANTIVIRUS",
    "UPDATES",
    "DOWNLOAD",

    // Devices - simple
    "TV",
    "RADIO",
    "STEREO",
    "HEADPHONES",
    "EARBUDS",
    "MICROPHONE",
    "WEBCAM",
    "MONITOR",
    "PROJECTOR",
    "SCREEN",

    // Social media - simple
    "POST",
    "LIKE",
    "SHARE",
    "FOLLOW",
    "SUBSCRIBE",
    "COMMENT",
    "MESSAGE",
    "GROUP",
    "PAGE",
    "PROFILE",
    "FRIEND",
    "FAMILY",
    "GROUP",
    "CHAT",
    "CALL",
    "VIDEO",
    "VOICE",
    "TEXT",
    "EMOJI",
    "STICKER",

    // Tech actions
    "BOOT",
    "START",
    "STOP",
    "PAUSE",
    "PLAY",
    "RECORD",
    "SAVE",
    "DELETE",
    "COPY",
    "PASTE",
    "CUT",
    "UNDO",
    "REDO",
    "FIND",
    "REPLACE",
    "SEARCH",
    "BROWSE",
    "DOWNLOAD",
    "UPLOAD",
    "STREAM",
  ],

  intermediate: [
    // Hardware components
    "PROCESSOR",
    "MOTHERBOARD",
    "GRAPHICS CARD",
    "SOUND CARD",
    "NETWORK CARD",
    "RANDOM ACCESS",
    "READ ONLY",
    "SOLID STATE",
    "HARD DRIVE",
    "OPTICAL DRIVE",
    "POWER SUPPLY",
    "HEAT SINK",
    "COOLING FAN",
    "CASE",
    "MODEM",
    "ROUTER",
    "SWITCH",
    "HUB",
    "REPEATER",
    "BRIDGE",
    "SENSOR",
    "ACTUATOR",
    "MICROCONTROLLER",
    "MICROPROCESSOR",
    "ACCELEROMETER",
    "GYROSCOPE",
    "GPS",
    "NFC",
    "RFID",
    "BIOMETRIC",

    // Software & Programming
    "OPERATING SYSTEM",
    "DATABASE",
    "ALGORITHM",
    "VARIABLE",
    "FUNCTION",
    "CLASS",
    "OBJECT",
    "ARRAY",
    "STRING",
    "INTEGER",
    "FLOAT",
    "BOOLEAN",
    "LOOP",
    "CONDITION",
    "STATEMENT",
    "EXCEPTION",
    "HANDLING",
    "DEBUGGING",
    "TESTING",
    "DEPLOYMENT",
    "FRONTEND",
    "BACKEND",
    "FULL STACK",
    "DEVOPS",
    "CI/CD",
    "AGILE",
    "SCRUM",
    "KANBAN",
    "WATERFALL",
    "SPRINT",
    "PYTHON",
    "JAVA",
    "JAVASCRIPT",
    "TYPESCRIPT",
    "RUBY",
    "PHP",
    "SWIFT",
    "KOTLIN",
    "RUST",
    "GO",
    "HTML",
    "CSS",
    "SQL",
    "JSON",
    "XML",
    "API",
    "SDK",
    "IDE",
    "CLI",
    "GUI",

    // Networks & Internet
    "ETHERNET",
    "FIBER OPTIC",
    "COAXIAL",
    "TWISTED PAIR",
    "SATELLITE",
    "5G",
    "LTE",
    "4G",
    "WIMAX",
    "ZIGBEE",
    "PROTOCOL",
    "TCP/IP",
    "HTTP",
    "HTTPS",
    "FTP",
    "SMTP",
    "POP3",
    "IMAP",
    "DNS",
    "DHCP",
    "FIREWALL",
    "PROXY",
    "VPN",
    "INTRANET",
    "EXTRANET",
    "DEMILITARIZED",
    "ZONE",
    "VLAN",
    "WAN",
    "LAN",

    // Cybersecurity
    "ENCRYPTION",
    "AUTHENTICATION",
    "AUTHORIZATION",
    "TWO FACTOR",
    "MULTI FACTOR",
    "BIOMETRIC",
    "TOKEN",
    "CERTIFICATE",
    "SIGNATURE",
    "HASH",
    "MALWARE",
    "RANSOMWARE",
    "SPYWARE",
    "ADWARE",
    "TROJAN",
    "WORM",
    "ROOTKIT",
    "KEYLOGGER",
    "PHISHING",
    "SPOOFING",

    // Social media advanced
    "INFLUENCER",
    "CONTENT CREATOR",
    "VIRAL",
    "ENGAGEMENT",
    "IMPRESSIONS",
    "REACH",
    "ANALYTICS",
    "MONETIZATION",
    "SPONSORSHIP",
    "BRAND DEAL",
    "TIKTOK",
    "INSTAGRAM",
    "FACEBOOK",
    "TWITTER",
    "LINKEDIN",
    "PINTEREST",
    "SNAPCHAT",
    "REDDIT",
    "QUORA",
    "MEDIUM",

    // Emerging tech
    "ARTIFICIAL INTELLIGENCE",
    "MACHINE LEARNING",
    "DEEP LEARNING",
    "NEURAL NETWORK",
    "NATURAL LANGUAGE",
    "COMPUTER VISION",
    "ROBOTICS",
    "AUTOMATION",
    "CHATBOT",
    "VIRTUAL ASSISTANT",
    "BLOCKCHAIN",
    "CRYPTOCURRENCY",
    "BITCOIN",
    "ETHEREUM",
    "SMART CONTRACT",
    "DISTRIBUTED LEDGER",
    "DECENTRALIZATION",
    "NON FUNGIBLE",
    "GAMIFICATION",
    "DIGITAL TWIN",
  ],

  hard: [
    // Hardware - Advanced/Scientific
    "MICROARCHITECTURE",
    "PIPELINING",
    "SUPERSCALAR",
    "OUT OF ORDER",
    "SPECULATIVE EXECUTION",
    "BRANCH PREDICTION",
    "CACHE COHERENCY",
    "MEMORY HIERARCHY",
    "VIRTUAL MEMORY",
    "PAGING",
    "INTERRUPT",
    "EXCEPTION",
    "TRAP",
    "SYSTEM CALL",
    "CONTEXT SWITCH",
    "SCHEDULING",
    "SYNCHRONIZATION",
    "DEADLOCK",
    "STARVATION",
    "RACE CONDITION",
    "QUANTUM COMPUTING",
    "QUBIT",
    "SUPERPOSITION",
    "ENTANGLEMENT",
    "QUANTUM GATE",
    "QUANTUM ALGORITHM",
    "SHOR'S ALGORITHM",
    "GROVER'S ALGORITHM",
    "QUANTUM SUPREMACY",
    "QUANTUM ERROR",

    // Programming - Advanced
    "COMPILER",
    "INTERPRETER",
    "ASSEMBLER",
    "LINKER",
    "LOADER",
    "PARSER",
    "LEXER",
    "SYNTAX TREE",
    "AST",
    "BYTECODE",
    "JIT COMPILATION",
    "AOT COMPILATION",
    "TYPES",
    "GENERICS",
    "TRAITS",
    "INTERFACE",
    "ABSTRACTION",
    "ENCAPSULATION",
    "INHERITANCE",
    "POLYMORPHISM",
    "COMPOSITION",
    "AGGREGATION",
    "DEPENDENCY INJECTION",
    "ASPECT ORIENTED",
    "FUNCTIONAL PROGRAMMING",
    "CONCURRENCY",
    "PARALLELISM",
    "ASYNC",
    "AWAIT",
    "PROMISE",
    "MICROSERVICES",
    "MONOLITHIC",
    "SOA",
    "EVENT DRIVEN",
    "MESSAGE QUEUE",
    "KAFKA",
    "RABBITMQ",
    "GRPC",
    "GRAPHQL",
    "REST API",

    // Networks - Advanced
    "OSI MODEL",
    "TCP/IP MODEL",
    "APPLICATION LAYER",
    "TRANSPORT LAYER",
    "NETWORK LAYER",
    "DATA LINK LAYER",
    "PHYSICAL LAYER",
    "SESSION LAYER",
    "PRESENTATION LAYER",
    "ENCRYPTION",
    "ROUTING PROTOCOL",
    "BGP",
    "OSPF",
    "EIGRP",
    "RIP",
    "ICMP",
    "ARP",
    "RARP",
    "DHCP",
    "NAT",
    "VLAN",
    "VXLAN",
    "MPLS",
    "VPN",
    "VPLS",
    "Ethernet",
    "InfiniBand",
    "Fibre Channel",
    "SAS",
    "SATA",

    // Cybersecurity - Advanced
    "ZERO TRUST",
    "ZERO DAY",
    "VULNERABILITY",
    "EXPLOIT",
    "PATCH",
    "MITIGATION",
    "INCIDENT RESPONSE",
    "FORENSICS",
    "PENETRATION TESTING",
    "SOC",
    "THREAT",
    "ATTACK VECTOR",
    "SURFACE",
    "PRIVILEGE ESCALATION",
    "ELEVATION",
    "LATERAL MOVEMENT",
    "COMMAND AND CONTROL",
    "EXFILTRATION",
    "DATA LOSS",
    "PROTECTION",
    "COMPLIANCE",
    "GDPR",
    "HIPAA",
    "PCI DSS",
    "SOX",
    "NIST",
    "ISO 27001",
    "SOC 2",
    "FISMA",
    "FEDRAMP",

    // Artificial Intelligence - Advanced
    "DEEP NEURAL NETWORK",
    "CONVOLUTIONAL NEURAL NETWORK",
    "RECURRENT NEURAL NETWORK",
    "LSTM",
    "GRU",
    "TRANSFORMER",
    "ATTENTION MECHANISM",
    "GPT",
    "BERT",
    "T5",
    "GENERATIVE ADVERSARIAL NETWORK",
    "DIFFUSION MODEL",
    "AUTOREGRESSIVE",
    "CAUSAL MODEL",
    "REINFORCEMENT LEARNING",
    "Q LEARNING",
    "DEEP Q NETWORK",
    "POLICY GRADIENT",
    "ACTOR CRITIC",
    "PPO",
    "COMPUTER VISION",
    "OBJECT DETECTION",
    "SEGMENTATION",
    "TRACKING",
    "SPATIAL",
    "TEMPORAL",
    "FUSION",
    "HALLUCINATION",
    "PROMPT ENGINEERING",
    "FINE TUNING",

    // Emerging Tech - Advanced
    "QUANTUM COMPUTING",
    "QUANTUM CRYPTOGRAPHY",
    "QKD",
    "POST QUANTUM",
    "LATTICE BASED",
    "CODE BASED",
    "HASH BASED",
    "ISOGENY BASED",
    "NIST STANDARDIZATION",
    "PQC",
    "WEB3",
    "METAVERSE",
    "AUGMENTED REALITY",
    "VIRTUAL REALITY",
    "MIXED REALITY",
    "EXtended",
    "HAPTIC",
    "SENSOR",
    "FUSION",
    "WEARABLE",
    "IoE",
    "CONNECTED",
    "SMART CITY",
    "SMART GRID",
    "INDUSTRIAL",
    "DIGITAL TWIN",
    "DIGITAL THREAD",
    "COMPUTATIONAL",
    "BIOHACKING",
    "NEURAL",
  ],
};
