export const travelWords = [
  // Places and Destinations
  'BEACH', 'MOUNTAIN', 'FOREST', 'DESERT', 'ISLAND',
  'CITY', 'COUNTRY', 'CONTINENT', 'OCEAN', 'RIVER',
  'LAKE', 'VALLEY', 'CANYON', 'VOLCANO', 'GLACIER',
  'TEMPLE', 'CASTLE', 'PALACE', 'PYRAMID', 'COLOSSEUM',
  'EiffelTower', 'TAJMAHAL', 'STATUE', 'CATHEDRAL', 'MOSQUE',
  // Travel Activities
  'EXPLORE', 'DISCOVER', 'WANDER', 'ADVENTURE', 'JOURNEY',
  'HIKING', 'CAMPING', 'CLIMBING', 'DIVING', 'SNORKELING',
  'SAILING', 'CYCLING', 'TREKKING', 'SKIING', 'SURFING',
  'PARAGLIDING', 'KAYAKING', 'RAFTING', 'ZIPLINE', 'BUNGEE',
  // Travel Essentials
  'PASSPORT', 'VISA', 'TICKET', 'LUGGAGE', 'BACKPACK',
  'SUITCASE', 'MAP', 'COMPASS', 'GUIDEBOOK', 'CAMERA',
  'TRAVELER', 'TOURIST', 'EXPLORER', 'ADVENTURER', 'VACATIONER',
  'ROADTRIP', 'CRUISE', 'FLIGHT', 'FERRY', 'TRAIN'
];