// src/modules/themes/word-lists/travel.ts
export const travelWords = {
  simple: [
    // Transportation
    "PLANE",
    "TRAIN",
    "BUS",
    "CAR",
    "BOAT",
    "SHIP",
    "BIKE",
    "SCOOTER",
    "TAXI",
    "TRUCK",
    "VAN",
    "JEEP",
    "CAB",
    "FERRY",
    "CRUISE",
    "YACHT",
    "SAIL",
    "ROW",
    "PADDLE",
    "WALK",
    "FLY",
    "DRIVE",
    "RIDE",
    "SAIL",
    "SWIM",
    "HIKE",
    "CAMP",
    "TOUR",
    "TRIP",
    "JOURNEY",

    // Places - simple
    "BEACH",
    "MOUNTAIN",
    "LAKE",
    "RIVER",
    "OCEAN",
    "FOREST",
    "DESERT",
    "ISLAND",
    "VALLEY",
    "HILL",
    "CITY",
    "TOWN",
    "VILLAGE",
    "CAPITAL",
    "PORT",
    "HARBOR",
    "AIRPORT",
    "STATION",
    "HOTEL",
    "HOSTEL",
    "CAMP",
    "PARK",
    "GARDEN",
    "ZOO",
    "MUSEUM",
    "CASTLE",
    "PALACE",
    "TEMPLE",
    "CHURCH",
    "MOSQUE",

    // Travel items - simple
    "SUITCASE",
    "BAG",
    "BACKPACK",
    "PASSPORT",
    "TICKET",
    "MAP",
    "COMPASS",
    "CAMERA",
    "PHONE",
    "WATCH",
    "SUNGLASSES",
    "HAT",
    "COAT",
    "BOOTS",
    "SHOES",
    "CLOTHES",
    "TOOTHBRUSH",
    "TOWEL",
    "SOAP",
    "LOTION",

    // Countries - simple
    "USA",
    "CANADA",
    "MEXICO",
    "BRAZIL",
    "UK",
    "FRANCE",
    "SPAIN",
    "ITALY",
    "GERMANY",
    "RUSSIA",
    "CHINA",
    "JAPAN",
    "INDIA",
    "AUSTRALIA",
    "EGYPT",
    "SOUTH AFRICA",
    "ARGENTINA",
    "PERU",
    "CHILE",
    "COLOMBIA",

    // Cities - simple
    "LONDON",
    "PARIS",
    "ROME",
    "MADRID",
    "BERLIN",
    "MOSCOW",
    "DUBAI",
    "TOKYO",
    "NEW YORK",
    "SYDNEY",
    "TORONTO",
    "MEXICO CITY",
    "CAIRO",
    "CAPE TOWN",
    "RIO",
    "BUENOS AIRES",
    "LIMA",
    "BOGOTA",
    "CARACAS",
    "PANAMA",

    // Landmarks - simple
    "PYRAMID",
    "STATUE",
    "TOWER",
    "BRIDGE",
    "COLUMN",
    "ARCH",
    "TEMPLE",
    "CHURCH",
    "CASTLE",
    "PALACE",
    "FALLS",
    "CANYON",
    "MOUNTAIN",
    "VOLCANO",
    "GLACIER",
    "GEYSER",
    "CAVE",
    "CLIFF",
    "BEACH",
    "DUNE",

    // Activities - simple
    "SWIMMING",
    "SNORKELING",
    "DIVING",
    "HIKING",
    "CLIMBING",
    "SKIING",
    "BOARDING",
    "CYCLING",
    "RUNNING",
    "WALKING",
    "SIGHTSEEING",
    "SHOPPING",
    "EATING",
    "DANCING",
    "SINGING",
    "PHOTOGRAPHY",
    "PAINTING",
    "READING",
    "WRITING",
    "RELAXING",

    // Food - simple
    "PASTA",
    "PIZZA",
    "TACO",
    "SUSHI",
    "CURRY",
    "STEAK",
    "BURGER",
    "FRIES",
    "SALAD",
    "SOUP",
    "CAKE",
    "BREAD",
    "RICE",
    "NOODLES",
    "DUMPLING",
    "PASTRY",
    "ICE CREAM",
    "CHOCOLATE",
    "FRUIT",
    "DRINK",
  ],

  intermediate: [
    // Countries - intermediate
    "UNITED STATES",
    "UNITED KINGDOM",
    "SOUTH KOREA",
    "NORTH KOREA",
    "SAUDI ARABIA",
    "IRAN",
    "IRAQ",
    "AFGHANISTAN",
    "PAKISTAN",
    "BANGLADESH",
    "MALAYSIA",
    "INDONESIA",
    "PHILIPPINES",
    "VIETNAM",
    "THAILAND",
    "CAMBODIA",
    "MYANMAR",
    "LAOS",
    "TURKEY",
    "GREECE",
    "TURKEY",
    "GREECE",
    "PORTUGAL",
    "NETHERLANDS",
    "BELGIUM",
    "SWITZERLAND",
    "AUSTRIA",
    "POLAND",
    "UKRAINE",
    "ROMANIA",
    "HUNGARY",
    "CROATIA",
    "SERBIA",
    "BULGARIA",
    "ALBANIA",
    "BOSNIA",
    "SLOVENIA",
    "SLOVAKIA",
    "CZECH",
    "CROATIA",
    "CHILE",
    "ARGENTINA",
    "PERU",
    "ECUADOR",
    "URUGUAY",
    "PARAGUAY",
    "BOLIVIA",
    "VENEZUELA",
    "GUYANA",
    "SURINAME",

    // Cities - intermediate
    "BANGKOK",
    "SINGAPORE",
    "KUALA LUMPUR",
    "JAKARTA",
    "MANILA",
    "HONG KONG",
    "SHANGHAI",
    "BEIJING",
    "SEOUL",
    "BANGALORE",
    "MUMBAI",
    "DELHI",
    "KARACHI",
    "LAGOS",
    "CAIRO",
    "PRETORIA",
    "NAIROBI",
    "TANZANIA",
    "MOROCCO",
    "ALGIERS",
    "TUNIS",
    "TRIPOLI",
    "NAIROBI",
    "DAR ES SALAAM",
    "ADDIS ABABA",
    "ACCRA",
    "LAGOS",
    "GHANA",
    "MALI",
    "NIGER",
    "COPENHAGEN",
    "OSLO",
    "STOCKHOLM",
    "HELSINKI",
    "REYKJAVIK",
    "DUBLIN",
    "EDINBURGH",
    "CARDIFF",
    "BELFAST",
    "DOVER",

    // Landmarks - intermediate
    "EIFFEL TOWER",
    "LEANING TOWER",
    "PYRAMIDS OF GIZA",
    "GRAND CANYON",
    "NIAGARA FALLS",
    "ULURU",
    "GREAT WALL",
    "TAJ MAHAL",
    "MACHU PICCHU",
    "ANCIENT ROME",
    "COLOSSEUM",
    "STONEHENGE",
    "GREAT BARRIER REEF",
    "MILKY WAY",
    "NORTHERN LIGHTS",
    "SOUTHERN LIGHTS",
    "MOUNT EVEREST",
    "K2",
    "MOUNT FUJI",
    "KILIMANJARO",
    "VICTORIA FALLS",
    "IGUACU FALLS",
    "ANGEL FALLS",
    "SANTIAGO",
    "PATAGONIA",
    "AMAZON",
    "ATACAMA",
    "SALAR DE UYUNI",
    "SAHARA",
    "GOBI",

    // Transportation - intermediate
    "BICYCLE",
    "MOTORCYCLE",
    "SCOOTER",
    "ELECTRIC SCOOTER",
    "TRANSFER",
    "TERMINAL",
    "GATE",
    "BOARDING",
    "TRANSIT",
    "ROAD",
    "HIGHWAY",
    "EXPRESSWAY",
    "TOLL",
    "TICKET",
    "PASSPORT",
    "VISA",
    "CUSTOMS",
    "IMMIGRATION",
    "ARRIVAL",
    "DEPARTURE",
    "LUGGAGE",
    "CAROUSEL",
    "CARGO",
    "BACKPACK",
    "DUFFEL",
    "TRUNK",
    "KNAPSACK",
    "SATCHEL",
    "BRIEFCASE",
    "WALLET",

    // Activities - intermediate
    "BACKPACKING",
    "TREKKING",
    "MOUNTAINEERING",
    "SNOWBOARDING",
    "KITESURFING",
    "WINDSURFING",
    "PARAGLIDING",
    "SKYDIVING",
    "BUNGEE JUMPING",
    "CLIFF DIVING",
    "SAFARI",
    "WHALE WATCHING",
    "BIRD WATCHING",
    "ASTROTOURISM",
    "ECOTOURISM",
    "AGROTOURISM",
    "CULTURAL TOURISM",
    "HISTORICAL TOURISM",
    "ADVENTURE TOURISM",
    "DARK TOURISM",
    "BUNGEE",
    "ZIP LINING",
    "CANYONING",
    "CAVING",
    "SPELUNKING",
    "SCUBA DIVING",
    "SNORKELLING",
    "FREEDIVING",
    "KAYAKING",
    "RAFTING",

    // Cuisine - intermediate
    "GASTRONOMY",
    "TAPAS",
    "MEZE",
    "SUSHI",
    "SASHIMI",
    "RAMEN",
    "PHO",
    "DIM SUM",
    "HOT POT",
    "YAKITORI",
    "PASTA",
    "PIZZA",
    "RISOTTO",
    "GELATO",
    "ESPRESSO",
    "CROISSANT",
    "BAGUETTE",
    "CHEESE",
    "CHOCOLATE",
    "WINE",
    "BEER",
    "WHISKY",
    "VODKA",
    "TEQUILA",
    "RUM",
    "GIN",
    "BRANDY",
    "COGNAC",
    "CHAMPAGNE",
    "PROSECCO",
  ],

  hard: [
    // Countries - full names
    "UNITED STATES OF AMERICA",
    "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
    "RUSSIAN FEDERATION",
    "PEOPLES REPUBLIC OF CHINA",
    "REPUBLIC OF INDIA",
    "FEDERATIVE REPUBLIC OF BRAZIL",
    "ISLAMIC REPUBLIC OF PAKISTAN",
    "REPUBLIC OF INDONESIA",
    "FEDERAL REPUBLIC OF NIGERIA",
    "ARAB REPUBLIC OF EGYPT",
    "REPUBLIC OF SOUTH AFRICA",
    "FEDERAL REPUBLIC OF GERMANY",
    "FRENCH REPUBLIC",
    "ITALIAN REPUBLIC",
    "KINGDOM OF SPAIN",
    "PORTUGUESE REPUBLIC",
    "KINGDOM OF THE NETHERLANDS",
    "KINGDOM OF BELGIUM",
    "SWISS CONFEDERATION",
    "REPUBLIC OF AUSTRIA",
    "REPUBLIC OF POLAND",
    "UKRAINE",
    "ROMANIA",
    "HUNGARY",
    "CROATIA",
    "SERBIA",
    "BULGARIA",
    "ALBANIA",
    "BOSNIA",
    "SLOVENIA",

    // Cities - with full names
    "BANGKOK",
    "SINGAPORE",
    "KUALA LUMPUR",
    "JAKARTA",
    "MANILA",
    "HONG KONG",
    "SHANGHAI",
    "BEIJING",
    "SEOUL",
    "BANGALORE",
    "MUMBAI",
    "DELHI",
    "KARACHI",
    "LAGOS",
    "CAIRO",
    "PRETORIA",
    "NAIROBI",
    "TANZANIA",
    "MOROCCO",
    "ALGIERS",
    "TUNIS",
    "TRIPOLI",
    "NAIROBI",
    "DAR ES SALAAM",
    "ADDIS ABABA",
    "ACCRA",
    "GHANA",
    "MALI",
    "NIGER",
    "MAURITANIA",
    "COPENHAGEN",
    "OSLO",
    "STOCKHOLM",
    "HELSINKI",
    "REYKJAVIK",
    "DUBLIN",
    "EDINBURGH",
    "CARDIFF",
    "BELFAST",
    "DOVER",

    // Landmarks - full names
    "EIFFEL TOWER",
    "LEANING TOWER OF PISA",
    "PYRAMIDS OF GIZA",
    "GRAND CANYON NATIONAL PARK",
    "NIAGARA FALLS",
    "ULURU - KATA TJUTA",
    "GREAT WALL OF CHINA",
    "TAJ MAHAL",
    "MACHU PICCHU",
    "ANCIENT ROME",
    "COLOSSEUM",
    "STONEHENGE",
    "GREAT BARRIER REEF",
    "MILKY WAY",
    "NORTHERN LIGHTS",
    "SOUTHERN LIGHTS",
    "MOUNT EVEREST",
    "K2",
    "MOUNT FUJI",
    "MOUNT KILIMANJARO",
    "VICTORIA FALLS",
    "IGUACU FALLS",
    "ANGEL FALLS",
    "SANTIAGO",
    "PATAGONIA",
    "AMAZON RAINFOREST",
    "ATACAMA DESERT",
    "SALAR DE UYUNI",
    "SAHARA DESERT",
    "GOBI DESERT",
    "DEAD SEA",
    "RED SEA",
    "ARABIAN SEA",
    "MEDITERRANEAN SEA",
    "CARIBBEAN SEA",
    "NORTH SEA",
    "BALTIC SEA",
    "BLACK SEA",
    "CASPIAN SEA",
    "PERSIAN GULF",

    // Travel Concepts - Advanced
    "INTERNATIONAL TOURISM",
    "DOMESTIC TOURISM",
    "SUSTAINABLE TOURISM",
    "RESPONSIBLE TOURISM",
    "ECOTOURISM",
    "GEOTOURISM",
    "REGENERATIVE TOURISM",
    "VOLUNTOURISM",
    "SLOW TOURISM",
    "CULINARY TOURISM",
    "HERITAGE TOURISM",
    "CULTURAL TOURISM",
    "URBAN TOURISM",
    "RURAL TOURISM",
    "COASTAL TOURISM",
    "WILDLIFE TOURISM",
    "SPACE TOURISM",
    "DARK TOURISM",
    "GHOST TOURISM",
    "NICHE TOURISM",
    "ITINERARY",
    "TRAVEL INSPIRATION",
    "TRAVEL ADDICTION",
    "FOMO",
    "DIGITAL NOMAD",
    "COUCHSURFING",
    "CAMPING",
    "GLAMPING",
    "WORKATION",
    "BLEISURE",

    // Transportation - Advanced
    "FREIGHTER TRAVEL",
    "CARGO SHIP",
    "CONTAINER SHIP",
    "BULK CARRIER",
    "TANKER",
    "PASSENGER SHIP",
    "CRUISE SHIP",
    "SAILING SHIP",
    "SHIPYARD",
    "DOCK",
    "AVIATION",
    "AEROSPACE",
    "AEROPLANE",
    "AIRSHIP",
    "ZEppelin",
    "BALLON",
    "HANG GLIDING",
    "PARASAILING",
    "PARAGLIDING",
    "WINGSUIT",
    "E SCOOTER",
    "E BIKE",
    "HOVERBOARD",
    "SEGWAY",
    "GYROSCOPE",
    "GUIDANCE",
    "NAVIGATION",
    "CARTOGRAPHY",
    "CHARTING",
    "TRACKING",
  ],
};
